### ISSUE TITLE
ログイン機能の実装

### ISSUE THREAD

**Issue by yuuki-nishino** [yuuki-nishino/shift-creation#5]
ログイン画面
src/app/login/template/login 以降のファイルでログイン画面を作成

src/app/login 下にログインの機能を持たせるように作成

[現段階で考えているプラン]
・Jason Web Token (JWT)を使う。
・Django REST FrameWork JWTというのがあるらしい。
・管理者かどうか判断する機能は後からでとりあえずユーザーログインできるように実装

**Comment by kinsann** [comment]
フォルダ構成を変更しました。
src/app/login/template/login 以降のファイルでログイン画面を作成
src/app/login 下にログインの機能を持たせるように作成
お願いします。

**Comment by yuuki-nishino** [comment]
テンプレートフォルダはsrc/app/template/loginもしくは、src/app/login/templateでいいのでは？

**Comment by kinsann** [comment]
@yuuki-nishino 確かにapp/templates/...という方がいいと思います。

**Comment by kinsann** [comment]
app/templates/...と修正してdevブランチにpushしました。
